/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TestLibGuiReusables;

import LibGuiReusables.*;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.TreeSelectionListener;

/**
 *
 * @author Javi
 */
public class CrearFactoriaArbol extends FormularioArbol implements ActionListener, ChangeListener, TreeSelectionListener {

    private static FormularioExtensible formularioExtensibleArbol;

    private static FormularioExtensible formularioExtensibleSimple;
    private static FormularioExtensible formularioExtensibleFichas;
    private static FormularioExtensible formularioExtensibleArbol2;

    private static FormSimpleDis0 formularioSimpleD0;
    private static FormSimpleDis1 formularioSimpleD1;
    private static FormSimpleDis2 formularioSimpleD2;
    private static FormSimpleDis3 formularioSimpleD3;
    private static FormSimpleDis4 formularioSimpleD4;
    private static FormSimpleDis5 formularioSimpleD5;
    private static ListaObservadoresEventos listaObs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void crearGUI() {
        incializar();

        formularioExtensibleArbol = FactoriaFormularios.crearFormulario(FormularioExtensible.TipoContenedor.ARBOL);

        formularioExtensibleArbol.setnombreContenedor("Factoria ARBOL");

        // crear lista observadores de eventos e incluir el formulario
        listaObs = new ListaObservadoresEventos();

        listaObs.nuevoActionListener(formularioExtensibleArbol);
        listaObs.nuevoChangeListener(formularioExtensibleArbol);
        formularioExtensibleArbol.setListaObservadores(listaObs);

        // CREAR FOMULARIO SIMPLE
        formularioExtensibleSimple = FactoriaFormularios.crearFormulario(FormularioExtensible.TipoContenedor.ARBOL);

        formularioExtensibleSimple.setnombreContenedor("formulario Conjunto");

        listaObs.nuevoActionListener(formularioExtensibleSimple);
        listaObs.nuevoChangeListener(formularioExtensibleSimple);
        formularioExtensibleSimple.setListaObservadores(listaObs);

        formularioSimpleD0 = new FormSimpleDis0();
        formularioSimpleD0.setListaObservadores(listaObs);

        formularioSimpleD1 = new FormSimpleDis1();
        formularioSimpleD1.setListaObservadores(listaObs);

        try {
            formularioExtensibleSimple.addHijoExtensible(formularioSimpleD0, "Formulario 1");
            formularioExtensibleSimple.addHijoExtensible(formularioSimpleD1, "Formulario 2");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(formularioExtensibleSimple, e.getMessage());
        }

        // CREAR FORMULARIO POR FICHAS
        formularioExtensibleFichas = FactoriaFormularios.crearFormulario(FormularioExtensible.TipoContenedor.ARBOL);

        formularioExtensibleFichas.setnombreContenedor("formulario Conjunto 2");

        listaObs.nuevoActionListener(formularioExtensibleFichas);
        listaObs.nuevoChangeListener(formularioExtensibleFichas);
        formularioExtensibleFichas.setListaObservadores(listaObs);

        formularioSimpleD2 = new FormSimpleDis2();
        formularioSimpleD2.setListaObservadores(listaObs);

        formularioSimpleD3 = new FormSimpleDis3();
        formularioSimpleD3.setListaObservadores(listaObs);

        try {
            formularioExtensibleFichas.addHijoExtensible(formularioSimpleD2, "Formulario 3");
            formularioExtensibleFichas.addHijoExtensible(formularioSimpleD3, "Formulario 4");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(formularioExtensibleFichas, e.getMessage());
        }

        // CREAR FOMULARIO arbol 2
        formularioExtensibleArbol2 = FactoriaFormularios.crearFormulario(FormularioExtensible.TipoContenedor.ARBOL);

        formularioExtensibleArbol2.setnombreContenedor("ARBOL 2");

        listaObs.nuevoActionListener(formularioExtensibleArbol2);
        listaObs.nuevoChangeListener(formularioExtensibleArbol2);
        formularioExtensibleArbol2.setListaObservadores(listaObs);

        formularioSimpleD4 = new FormSimpleDis4();
        formularioSimpleD4.setListaObservadores(listaObs);

        formularioSimpleD5 = new FormSimpleDis5();
        formularioSimpleD5.setListaObservadores(listaObs);

        try {
            formularioExtensibleArbol2.addHijoExtensible(formularioSimpleD4, "Formulario 5");
            formularioExtensibleArbol2.addHijoExtensible(formularioSimpleD5, "Formulario 6");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(formularioExtensibleArbol2, e.getMessage());
        }

        // AGREGAR HIJOS A FOMULARIO PRINCIPAL
        try {
            formularioExtensibleArbol.addHijoExtensible(formularioExtensibleSimple, formularioExtensibleSimple.getnombreContenedor());
            formularioExtensibleArbol.addHijoExtensible(formularioExtensibleFichas, formularioExtensibleFichas.getnombreContenedor());
            formularioExtensibleArbol.addHijoExtensible(formularioExtensibleArbol2, formularioExtensibleArbol2.getnombreContenedor());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(formularioExtensibleArbol, e.getMessage());
        }

        formularioExtensibleArbol.configurarFormulario();
        formularioExtensibleArbol.setVisible(true);

    }

    private static void incializar() {
        formularioExtensibleArbol = null;
        formularioExtensibleSimple = null;
        formularioExtensibleFichas = null;
        formularioSimpleD0 = null;
        formularioSimpleD1 = null;
        formularioSimpleD2 = null;
        formularioSimpleD3 = null;
        formularioSimpleD4 = null;
        formularioSimpleD5 = null;
        listaObs = null;;

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void actionPerformed(ActionEvent evt) {
        System.out.println("Botón pulsado: " + evt.getActionCommand());
        if (evt.getActionCommand().equals("Aceptar")) {
            aceptar();
        } else if (evt.getActionCommand().equals("Cancelar")) {
            cancelar();
        }
    }

    @Override
    public void stateChanged(ChangeEvent evt) {
        JSpinner s = (JSpinner) evt.getSource();

        formularioSimpleD0.recuperarValorExterno("jSpinner1", s.getValue().toString());

    }

}
