package TestLibGuiReusables;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import LibGuiReusables.*;
import LibGuiReusables.revision.Observador;

import javax.swing.JOptionPane;

/**
 *
 * @author Javi
 */
public class CrearPruebaAmpliada extends FormularioPorFichas implements Observador {

    private static FormularioExtensible formularioExtensiblePorFichas;

    private static Prueba formularioSimpleD0;
    private static PruebaAmpliada formularioSimpleD1;

    // private static FormularioExtensible formularioPruebaBasica ;
    // private static ListaObservadoresEventos listaObs;
    public FormularioExtensible CrearPruebaAmpliada() {
        initComponents();

        FormularioExtensible retorno;
        retorno = FactoriaFormularios.crearFormulario(FormularioExtensible.TipoContenedor.PORFICHAS);
        return retorno;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static FormularioExtensible crearGUI() {
        incializar();

        // CREAR FORMULARIO PRINCIPAL
        formularioExtensiblePorFichas = new CrearPruebaAmpliada();
        formularioExtensiblePorFichas.setnombreContenedor("Prueba Ampliada");

        
        formularioSimpleD0 = new Prueba();
        formularioSimpleD1 = new PruebaAmpliada();
        
        FormularioExtensible.getGestorEventos().addObservador("CambiarValor", formularioExtensiblePorFichas);
        FormularioExtensible.getGestorEventos().addObservador("CambiarValor", formularioSimpleD0);
        FormularioExtensible.getGestorEventos().addObservador("CambiarValor", formularioSimpleD1);
        
        try {
            formularioExtensiblePorFichas.addHijoExtensible(formularioSimpleD0, "Datos Basicos");
            formularioExtensiblePorFichas.addHijoExtensible(formularioSimpleD1, "Datos Ampliados");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(formularioExtensiblePorFichas, e.getMessage());
        }
        return (formularioExtensiblePorFichas);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private static void incializar() {

        formularioExtensiblePorFichas = null;

        formularioSimpleD0 = null;
        formularioSimpleD1 = null;

    }

    @Override
    public void guardar() {
        super.guardar();
        JOptionPane.showMessageDialog(this, "Se ha guardado la Prueba Ampliada");

    }

}
