package TestLibGuiReusables;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import LibGuiReusables.*;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

import javax.swing.event.ChangeListener;

/**
 *
 * @author Javi
 */
public class CrearPruebaBasica extends FormularioSimple implements ActionListener, ChangeListener {

    private static FormularioExtensible formularioExtensibleSimple;

    private static Prueba formularioSimpleD0;
    private static PruebaBasica formularioSimpleD1;

    private static ListaObservadoresEventos listaObs;

    public FormularioExtensible CrearPruebaBasica() {
        initComponents();

        FormularioExtensible retorno;
        retorno = FactoriaFormularios.crearFormulario(FormularioExtensible.TipoContenedor.SIMPLE);
        return retorno;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void crearGUI() {
        incializar();

        // CREAR FORMULARIO PRINCIPAL
        formularioExtensibleSimple = new CrearPruebaBasica();

        //formularioExtensibleSimple.setnombreContenedor("Factoria SIMPLE");
        // crear lista observadores de eventos e incluir el formulario
        listaObs = new ListaObservadoresEventos();
        listaObs.nuevoActionListener(formularioExtensibleSimple);
        listaObs.nuevoChangeListener(formularioExtensibleSimple);

        formularioExtensibleSimple.setListaObservadores(listaObs);

        formularioSimpleD0 = new Prueba();
        formularioSimpleD0.setListaObservadores(listaObs);
       // formularioSimpleD0.configurarFormulario(false);

        formularioSimpleD1 = new PruebaBasica();
        formularioSimpleD1.setListaObservadores(listaObs);
     //   formularioSimpleD1.configurarFormulario(false);

        try {
            formularioExtensibleSimple.addHijoExtensible(formularioSimpleD0, formularioSimpleD0.getnombreContenedor());
            formularioExtensibleSimple.addHijoExtensible(formularioSimpleD1, formularioSimpleD1.getnombreContenedor());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(formularioExtensibleSimple, e.getMessage());
        }

        formularioExtensibleSimple.configurarFormulario(true);
        formularioExtensibleSimple.setVisible(true);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private static void incializar() {

        formularioExtensibleSimple = null;

        formularioSimpleD0 = null;
        formularioSimpleD1 = null;

        listaObs = null;;

    }

}
