package TestLibGuiReusables;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import LibGuiReusables.*;
import LibGuiReusables.Observador;

import javax.swing.JOptionPane;

/**
 *
 * @author Javi
 */
public class CrearPruebaBasica extends FormularioSimple implements Observador {

    private static FormularioExtensible formularioExtensibleSimple;

    private static Prueba formularioSimpleD0;
    private static PruebaBasica formularioSimpleD1;

    //private static ListaObservadoresEventos listaObs;
    public FormularioExtensible CrearPruebaBasica() {
        initComponents();

        FormularioExtensible retorno;
        FactoriaFormularioExtensible fabricaFormulario = FactoriaFormularioExtensible.getInstancia();
        retorno = fabricaFormulario.crearFormulario(FormularioExtensible.TipoFormulario.SIMPLE);
        return retorno;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static FormularioExtensible crearGUI(GestorEventos gesEven) {
        incializar();

        GestorEventos gestorEventos;
        if (gesEven == null) {
            gestorEventos = new GestorEventos();
        } else {
            gestorEventos = gesEven;
        }
        // CREAR FORMULARIO PRINCIPAL
        formularioExtensibleSimple = new CrearPruebaBasica();
        formularioExtensibleSimple.setGestorEventos(gestorEventos);
        formularioExtensibleSimple.setnombreContenedor("Prueba Basica");

        formularioSimpleD0 = new Prueba();
        formularioSimpleD0.setGestorEventos(gestorEventos);
        formularioSimpleD1 = new PruebaBasica();
        formularioSimpleD1.setGestorEventos(gestorEventos);

        formularioExtensibleSimple.getGestorEventos().addObservador("CambiarValor", formularioExtensibleSimple);
        formularioExtensibleSimple.getGestorEventos().addObservador("CambiarValor", formularioSimpleD0);
        formularioExtensibleSimple.getGestorEventos().addObservador("CambiarValor", formularioSimpleD1);

        try {
            formularioExtensibleSimple.addHijoExtensible(formularioSimpleD0, formularioSimpleD0.getnombreContenedor());
            formularioExtensibleSimple.addHijoExtensible(formularioSimpleD1, formularioSimpleD1.getnombreContenedor());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(formularioExtensibleSimple, e.getMessage());
        }

        return (formularioExtensibleSimple);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private static void incializar() {

        formularioExtensibleSimple = null;

        formularioSimpleD0 = null;
        formularioSimpleD1 = null;

        //listaObs = null;
    }

    @Override
    public void guardar() {
        super.guardar();
        JOptionPane.showMessageDialog(this, "Se ha guardado la Prueba Basica");

    }

}
