package TestLibGuiReusables;

import LibGuiReusables.IComunicable;
import LibGuiReusables.IValidable;
import java.awt.event.ActionListener;
import javax.swing.event.ChangeListener;

public class FormSimpleDis0 extends LibGuiReusables.LibFormularioSimple implements ActionListener, ChangeListener,IValidable, IComunicable {

//    private LibListaObservadoresEventos observadores;

    /**
     * Creates new form Find
     *
     */
    public FormSimpleDis0() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Find");

        jPanel1.setMinimumSize(new java.awt.Dimension(531, 73));
        jPanel1.setLayout(null);

        jLabel1.setText("Find What:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(12, 4, 63, 16);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(80, 1, 349, 22);

        jCheckBox1.setText("Match Case");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(80, 32, 87, 17);

        jCheckBox2.setText("Wrap Around");
        jCheckBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(184, 32, 97, 17);

        jCheckBox3.setText("Whole Words");
        jCheckBox3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(80, 56, 97, 17);

        jCheckBox4.setText("Search Backwards");
        jCheckBox4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel1.add(jCheckBox4);
        jCheckBox4.setBounds(184, 56, 125, 17);

        jButton1.setText("Find");
        jPanel1.add(jButton1);
        jButton1.setBounds(436, 0, 71, 25);

        jButton2.setText("Cancel");
        jPanel1.add(jButton2);
        jButton2.setBounds(436, 32, 71, 25);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cambiarValor(String nombreComponente, Object valor) {
        System.out.println("cambiar valor");

        if ("jCheckBox4".equals(nombreComponente)) {

            jCheckBox4.setSelected((Boolean) valor);

        }
    }

    @Override
    public void recuperarValorExterno(String nombreComponente, Object valor) {

        if ("jSpinner1".equals(nombreComponente)) {
            jTextField1.setText((String) valor);

        }
        System.out.println("recuperar valor");
    }

   

   
}
