/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TestLibGuiReusables;

/**
 *
 * @author Javi
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    private static MenuPrincipal menuPrincipal;

    public MenuPrincipal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();
        botonCrearFactoriaSimple = new javax.swing.JButton();
        botonCrearFactoriaPorFichas = new javax.swing.JButton();
        botonCrearFactoriaSimpleLista = new javax.swing.JButton();
        botonCrearFactoriaPorFichasLista = new javax.swing.JButton();
        botonCrearFactoriaaArbol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonCrearFactoriaSimple.setText("Crear Factoria Simple");
        botonCrearFactoriaSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearFactoriaSimpleActionPerformed(evt);
            }
        });

        botonCrearFactoriaPorFichas.setText("Crear Factoria por Fichas");
        botonCrearFactoriaPorFichas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearFactoriaPorFichasActionPerformed(evt);
            }
        });

        botonCrearFactoriaSimpleLista.setText("Crear Factoria Simple con Lista");
        botonCrearFactoriaSimpleLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearFactoriaSimpleListaActionPerformed(evt);
            }
        });

        botonCrearFactoriaPorFichasLista.setText("Crear Factoria por Fichas con Lista");
        botonCrearFactoriaPorFichasLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearFactoriaPorFichasListaActionPerformed(evt);
            }
        });

        botonCrearFactoriaaArbol.setText("Crear Factoria Arbol");
        botonCrearFactoriaaArbol.setActionCommand("Crear Factoria Arbol");
        botonCrearFactoriaaArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearFactoriaaArbolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botonCrearFactoriaSimpleLista, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(botonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCrearFactoriaSimple, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(botonCrearFactoriaPorFichas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCrearFactoriaPorFichasLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCrearFactoriaaArbol, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                .addGap(0, 68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(botonCrearFactoriaSimple)
                .addGap(18, 18, 18)
                .addComponent(botonCrearFactoriaSimpleLista)
                .addGap(18, 18, 18)
                .addComponent(botonCrearFactoriaPorFichas)
                .addGap(18, 18, 18)
                .addComponent(botonCrearFactoriaPorFichasLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonCrearFactoriaaArbol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(botonSalir)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonCrearFactoriaSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearFactoriaSimpleActionPerformed
        desactivarBotones();
        CrearFactoriaSimple.crearGUI();
    }//GEN-LAST:event_botonCrearFactoriaSimpleActionPerformed

    private void botonCrearFactoriaPorFichasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearFactoriaPorFichasActionPerformed
        desactivarBotones();
        CrearFactoriaPorFichas.crearGUI();
    }//GEN-LAST:event_botonCrearFactoriaPorFichasActionPerformed

    private void botonCrearFactoriaSimpleListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearFactoriaSimpleListaActionPerformed
        desactivarBotones();
        CrearFactoriaSimpleLista.crearGUI();
    }//GEN-LAST:event_botonCrearFactoriaSimpleListaActionPerformed

    private void botonCrearFactoriaPorFichasListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearFactoriaPorFichasListaActionPerformed
        desactivarBotones();
        CrearFactoriaPorFichasLista.crearGUI();
    }//GEN-LAST:event_botonCrearFactoriaPorFichasListaActionPerformed

    private void botonCrearFactoriaaArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearFactoriaaArbolActionPerformed
        desactivarBotones();
        CrearFactoriaArbol.crearGUI();
    }//GEN-LAST:event_botonCrearFactoriaaArbolActionPerformed

    private void desactivarBotones() {
        /*
        menuPrincipal.botonCrearFactoriaSimple.setEnabled(false);
        menuPrincipal.botonCrearFactoriaSimpleLista.setEnabled(false);
        menuPrincipal.botonCrearFactoriaPorFichas.setEnabled(false);        
        menuPrincipal.botonCrearFactoriaPorFichasLista.setEnabled(false);
        menuPrincipal.botonCrearFactoriaArbol.setEnabled(false);
         */
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                menuPrincipal = new MenuPrincipal();
                menuPrincipal.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearFactoriaPorFichas;
    private javax.swing.JButton botonCrearFactoriaPorFichasLista;
    private javax.swing.JButton botonCrearFactoriaSimple;
    private javax.swing.JButton botonCrearFactoriaSimpleLista;
    private javax.swing.JButton botonCrearFactoriaaArbol;
    private javax.swing.JButton botonSalir;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
